### ISSUE TITLE
Back-references not refreshing

### ISSUE THREAD

**Issue by ghost** [jgeewax/gaetestbed#6]
I recently changed one of my property names from 'ref_obj' to 'refobj'. Now when I run my unit tests, some fail because the auto-generated back-reference is still looking for 'ref_obj' instead of the new name. 

I know GAETestbed removes entities between tests, but does it update/remove indexes? Is there a way to dump the datastore file it uses and start fresh?

**Comment by jgeewax** [comment]
The DataStoreTestCase calls the internal .Clear() method (http://code.google.com/p/googleappengine/source/browse/trunk/python/google/appengine/api/datastore_file_stub.py#462) on the datastore stub rather than creating a new one (http://github.com/jgeewax/gaetestbed/blob/master/gaetestbed/datastore.py#L103), so it's definitely possible that indexes are not being updated nor removed.

Can you give me a better idea of the order of events leading up to your error (step by step kind of thing)? If it looks like a legitimate problem, instead of calling .Clear() we could change the code to destroy and re-create a new datastore stub which may fix the problem.

**Comment by ghost** [comment]
Background: As I mentioned, I have Comment model with a property 'ref_obj' that keeps a reference to the entity being commented on (ultimately resolves to db.Key). 
1. I changed the name of of 'ref_obj' to 'refobj' in the model. 
2. I updated all references in my tests to use 'refobj'. 
3. I ran nosetests. All tests passed except for one involving an auto-generated back-reference called 'comments' (called like this 'entity.comments). The output shows that the generated GQL is still trying to use 'ref_obj' to construct the query. 
4. I cleared the datastore for my webapp. 
5. I ran nosetests again - same result. 
6. I updated the index.yaml file to NOT generate the index automatically. 
7. I ran nosetests again - same result. 

After doing manual functional tests on the webapp, I noticed that a new index was automatically generated even if I placed the model above the AUTOGENERATED line. 

Thank you for your help. Please let me know if you need any more details.

**Comment by jgeewax** [comment]
Each time you run nosetests is a separate process, meaning the test datastore should be cleared (unless you're passing an argument to nose telling it where the datastore file is located). I don't think there's anything GAE Testbed can do specifically to reset things further.

**Comment by ghost** [comment]
The issue seems to be resolved. Thank you for your help and some insight into Testbed's workings. It's a great tool.
